{% set name = "git-filter-repo" %}
{% set version = "2.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 411b27e68a080c07a69c233cb526dbc2d848b09a72f10477f4444dd0822cf290

build:
  entry_points:
    - git-filter-repo = git_filter_repo:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - git >=2.26.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show git-filter-repo
    # check entry point
    - git-filter-repo --version
    # check git integration
    - git filter-repo --version

about:
  home: https://github.com/newren/git-filter-repo
  summary: Quickly rewrite git repository history
  dev_url: https://github.com/newren/git-filter-repo
  license: MIT
  license_file: COPYING.mit

extra:
  recipe-maintainers:
    - duncanmmacleod
